/* NECESSARY SKILL SCHEMA */
CREATE TABLE IF NOT EXISTS necessary_skill (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

/* ADDITIONAL SKILL SCHEMA */
CREATE TABLE IF NOT EXISTS additional_skill (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);