server:
  port: 9001

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:3306/user_service
    username: root
    password: ${MYSQL_ROOT_PASSWORD:defaultPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always